version: "3"

tasks:
  build:
    cmds:
      - docker build . -t ghcr.io/sandbox-pokhara/hrms-frontend

  publish:
    cmds:
      - docker image push ghcr.io/sandbox-pokhara/hrms-frontend

  deploy:
    cmds:
      - ssh sandbox-ovh -t "cd hrms && docker compose pull && docker compose up -d"
