services:
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=hrms
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    image: ghcr.io/sandbox-pokhara/hrms-backend
    environment:
      - DEBUG=True
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_DB=hrms
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - ALLOWED_HOSTS=localhost,backend
      - CSRF_TRUSTED_ORIGINS=http://localhost:3000,http://backend:8000
      - SECRET_KEY=STRONG_KEY
      - TIME_ZONE=UTC
    depends_on:
      db:
        condition: service_healthy
  frontend:
    image: ghcr.io/sandbox-pokhara/hrms-frontend
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
