# Generated by Django 5.0.7 on 2024-08-05 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_absencebalance_delta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absencebalance',
            name='created_by',
        ),
    ]
